name: crystal
on:
  push:
    branches:
      - main
jobs:
  buildContainerImage:
    runs-on: ubuntu-20.04

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/141083904817/locations/global/workloadIdentityPools/crystal-pool/providers/crystal-provider'
          service_account: 'actions@ca-tominaga.iam.gserviceaccount.com'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Configure docker for artifact registry'
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/ca-tominaga/crystal/nginx:stable-alpine
