name: gke
on: workflow_dispatch
jobs:
  deployGKE:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/141083904817/locations/global/workloadIdentityPools/crystal-pool/providers/crystal-provider'
          service_account: 'actions@ca-tominaga.iam.gserviceaccount.com'

      - id: 'get-gke-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'crystal'
          location: 'asia-northeast1'

      - id: 'get secret'
        run: 'gcloud secrets versions access latest --secret="CRYSTAL_SECRET"'

      - id: 'get pods'
        run: 'kubectl get pods --all-namespaces'
