name: gke
on: workflow_dispatch
jobs:
  deployGKE:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/141083904817/locations/global/workloadIdentityPools/crystal-pool/providers/crystal-provider'
          service_account: 'actions@ca-tominaga.iam.gserviceaccount.com'

      - id: 'get-gke-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'crystal'
          location: 'asia-northeast1'

      - name: 'configure-docker'
        run: 'gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet'

      - name: 'build docker image'
        run: |-
          docker build \
            --tag "asia-northeast1-docker.pkg.dev/$GOOGLE_CLOUD_PROJECT/crystal/nginx:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            .

      - name: 'push docker image'
        run: |-
          docker push "asia-northeast1-docker.pkg.dev/$GOOGLE_CLOUD_PROJECT/crystal/nginx:$GITHUB_SHA" 

      - name: 'get secrets'
        run: |-
          export CRYSTAL_SECRET=`gcloud secrets versions access latest --secret="CRYSTAL_SECRET"`
          echo $CRYSTAL_SECRET

      - name: 'replace IMAGE and SECRETS'
        run: |-
          sed -i -e s/IMAGE/"asia-northeast1-docker.pkg.dev\/$GOOGLE_CLOUD_PROJECT\/crystal\/nginx:$GITHUB_SHA"/g kubernetes/nginx.yaml
          sed -i -e s/CRYSTAL_SECRET_VALUE/$CRYSTAL_SECRET/g kubernetes/nginx.yaml
          cat kubernetes/nginx.yaml

      - name: 'deploy nginx'
        run: 'kubectl apply -f kubernetes/nginx.yaml'
